version: 2.44.2.{build}
image: Visual Studio 2019
configuration: Release
platform: x64

branches:
  only:
    - develop
    - master

install:
  - git submodule update --init

init:
  - cmd: cmake --version

build_script:
  - mkdir build32
  - cd build32
  - cmake .. -A Win32 -DVERSION={version} -DDATE="2020-12-07"
  - cmake --build . --config Release --target dot
  - cd ..

  - mkdir build64
  - cd build64
  - cmake .. -A x64 -DVERSION={version} -DDATE="2020-12-07"
  - cmake --build . --config Release --target dot
  - cd ..

artifacts:
  - path: build32/cmd/dot/Release/dot.exe
  - path: build64/cmd/dot/Release/dot.exe
